config:
  log_iterations: 100 # How often do you want to log the training stats
  image_display_iterations: 250 # How often do you want to display output images during training
  image_save_iterations: 2500 # How often do you want to save output images during training
  test_every_iterations: 1000 # How often do you want to test trained models
  hyperparameters:
    trainer: Trainer
    ll_direct_link_w: 100
    kl_direct_link_w: 0.1
    ll_cycle_link_w: 100
    kl_cycle_link_w: 0.1
    z_recon_w: 0.1
    gan_w: 10
    control_w: 1.0
    batch_size: 64
    seed: 30
    iterations: 10000
    gen:
      ch: 64
      input_dim: 3
      n_enc_front_blk: 3
      n_enc_res_blk: 3
      n_enc_shared_blk: 1
      n_dec_shared_blk: 1
      n_dec_res_blk: 3
      n_dec_front_blk: 3
      res_dropout_ratio: 0.5
      norm_layer: instance_norm
      optimizer:
        lr_schedule_class: ConstantSchedule
        lr: 1e-4
        method: adam
        beta_1: 0.5
        beta_2: 0.999
    dis:
      ch: 64
      input_dim: 3
      n_layer: 4
      norm_layer: instance_norm
      optimizer:
        lr_schedule_class: ConstantSchedule
        lr: 1e-4
        method: adam
        beta_1: 0.5
        beta_2: 0.999
    control:
      n_layer: 3
      fc_layers: [16]
      loss: mse
      optimizer:
        lr_schedule_class: ConstantSchedule
        lr: 1e-2
        method: sgd
  datasets:
    general:
      datasets_dir: /home/zerogerc/msazanovich/duckietown-data
      load_size: [32, 64] # height, width
      crop_size: [32, 64] # height, width
    domain_a:
      dataset_path: episode_1438/loop_empty_patched
    domain_b:
      dataset_path: logs/duckietown
